name: Django Github actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with: 
          # Used to fetch specific version of python
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py collectstatic

      - name: Running Test Django
        run: |
          python manage.py test

  build-docker-image:
    runs-on: ubuntu-20.04
    name: Build Image
    needs: [build]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker build -f ./Dockerfile . -t django-app:latest
